### ISSUE TITLE
Azure Bot channel error “There was an error sending this message to your bot: HTTP status code Unauthorized”

### ISSUE THREAD

**Issue by atifgk** [pulumi/pulumi-azuread#115]
Hi,

I have created Azure application and Bot channel with pulumi using [this link](https://www.pulumi.com/docs/reference/pkg/azuread/application/). But i'm getting Unauthorized error when try this application with Bot. i have tried **Oauth2AllowImplicitFlow = false** parameter but pulumi still add implicit grant setting

![image](https://user-images.githubusercontent.com/11180268/96080816-59a6f600-0ed1-11eb-890d-8f2ed4ce260b.png)

If I disable Implicit Grant setting from azure portal then Bot channel works fine. can you please guide how i can avoid this implicit grant setting from pulumi? thanks

**Comment by leezen** [comment]
I believe the issue is not `Oauth2AllowImplicitFlow` but as the warning message says having the redirect URI set. Do you have anything set for `replyUrls`?

**Comment by atifgk** [comment]
yes i tried setting replyUrls parameter but no success. If i uncheck both Access token and Id tokens checkbox in implicit grant then after saving application start working as it disable Implicit Grant

**Comment by atifgk** [comment]
Issue is solved by setting valid replyUrls
