### ISSUE TITLE
Consider generating EntraID (azureAD) provider from API instead of terraform bridge

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/pulumi-azuread#1287]
Hi,
would you consider the creation of MSGraph provider similar to Azure-native?

Reasons: 
* Microsoft is transitioning to generated SDKs and MSGraph APIs have 2 versions stable & beta https://github.com/microsoftgraph/msgraph-metadata/tree/master/openapi. 
  * IIUC [kiota](https://github.com/microsoft/kiota) is the main project for generating SDKs and #1023 is already considering migrating towards the new azidentity (go package, but is similar in other languages) 
* The current terraform provider depends on manually implemented resources (AFAIK) which drastically limits the speed of  adoption of new resources
   * Almost all issues here are caused by the upstream provider.

My current use case requires both API versions because v1 lacks some properties in beta and is impossible to achieve with the terraform provider. I am trying to orchestrate line SAML between AWS & AWS Workspaces and AzureAD which turned out to be a complicated task if one doesn't want to do it manually. The APIs on both sides have limitations but the current azureAD TF provider adds on top of that. 
So I may end up writing my provider or several dynamic providers. 
See example issue: hashicorp/terraform-provider-azuread/issues/1418

**Comment by 1oglop1** [comment]
@mjeffryes Yes, I learned that a few days after posting this. 
I think when #1416 is resolved, this issue can be closed.

**Comment by mjeffryes** [comment]
https://github.com/pulumi/pulumi-azuread/issues/1416 is in the latest release: https://github.com/pulumi/pulumi-azuread/issues/1416#issuecomment-2407353219
