### ISSUE TITLE
Which provider to include inside CustomResourceOptions

### ISSUE THREAD

**Issue by PawelStadnicki** [pulumi/pulumi-azuread#138]
If I'm not mistaken I just need a confirmation rather than a clue.
When I create AD artefact (ServicePrincipal, RoleAssigment etc) I have an option to pass CustomResourceOptions 
in cosntructor, same as for provisiong other Azure resources.

I need to use custom options in order to pass subscription id as we have many of them.
SubscriptionId should be passed inside the provider so my question is: can it be any of the two Pulumi.Azure.Provider or Pulumi.AzureNextGen.Provider correct? Proper provider type play role when provisioning resources but with AD it can by any ?

Subscription & AD mix is a little bit opaque, you can't see it easily on Azure Portal I guess and by accident we can ommit it also with Pulumi. If subscription expires then principals lost access. So if I will not pass proper subscription id it will be taken from default (set by 'az account set') which may cause dramatic effects

**Comment by mikhailshilkov** [comment]
It has to be the provider from the same assembly where the resource is defined. In this case, https://github.com/pulumi/pulumi-azuread/blob/master/sdk/dotnet/Provider.cs

**Comment by PawelStadnicki** [comment]
> It has to be the provider from the same assembly where the resource is defined. In this case, https://github.com/pulumi/pulumi-azuread/blob/master/sdk/dotnet/Provider.cs

but that particular provider args (Pulumi.AzureAD.ProviderArgs) don't have option to specify  SubscriptionId 
so how I can provide it?

**Comment by mikhailshilkov** [comment]
Why do you need to? Azure AD objects aren't linked to a particular subscription.

**Comment by PawelStadnicki** [comment]
> Why do you need to? Azure AD objects aren't linked to a particular subscription.

Ok, you are right.
What about this: [https://www.pulumi.com/docs/reference/pkg/azure/authorization/]
This group is on the edge between AAD and recources.
Do I have to pass proper provider with subscription id there?
That resources have some scope tied to particular subscription like RoleDefinitionId.

**Comment by mikhailshilkov** [comment]
Yes, there you need to pass the provider from the same package (azure)
