### ISSUE TITLE
Service principal secret update - change is visible in pulumi preview

### ISSUE THREAD

**Issue by vigor-vavan** [pulumi/pulumi-azuread#1475]
### Describe what happened

When changing the secret for a service principal in the AzureAD provider, the new secret is displayed in plain text. In contrast, updates in the azure_native and azure providers are marked as secrets.

![Image](https://github.com/user-attachments/assets/8f747ee6-0332-4d1a-a64a-acf6fb835495)

### Sample program

```python
custom_provider = azure_native.Provider(
        "custom_provider",
        subscription_id=customer_subscription_id,
        client_id=os.environ.get('CLIENT_ID'),
        client_secret=os.environ.get('CLIENT_SECRET'),
        tenant_id=os.environ.get('TENANT_ID'),
    )
    management_provider = azure_native.Provider(
        "management_provider",
        subscription_id=customer_subscription_id,
        client_id=os.environ.get('CLIENT_ID'),
        client_secret=os.environ.get('CLIENT_SECRET'),
        tenant_id=os.environ.get('TENANT_ID'),
    )
    azure_ad = pulumi_azuread.Provider(
        "azure_provider",
        client_id=os.environ.get('CLIENT_ID'),
        client_secret=os.environ.get('CLIENT_SECRET'),
        tenant_id=os.environ.get('TENANT_ID'),
        metadata_host="",
    )
```

### Affected Resource(s)

pulumi providers

### Output of `pulumi about`

```
python version 3.11.1
pulumi version 3.134.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Hi @vigor-vavan thanks for writing this up.

I've reviewed our provider code and have confirmed that we mark this configuration variable as a secret: https://github.com/pulumi/pulumi-azuread/blob/d8494ba0accedfa970d27ae70b9d4fb7957271f6/provider/resources.go#L153-L155

What version of the pulumi-azuread provider are you using?

If you check your state file, do you see the `clientSecret` on the `azure_provider` with plain text or encypted? This will help us narrow down if it's an issue in the schema, provider or engine.

To note, you can also work around this by not explicitly setting these variables in the constructor and letting the provider read directly from your environment variables (e.g. `ARM_CLIENT_SECRET`).  See the [configuration options](https://www.pulumi.com/registry/packages/azuread/installation-configuration/#configuration-options).

**Comment by thomas11** [comment]
Client secret was marked as a secret in [release v5.53.2](https://api.github.com/repos/pulumi/pulumi-azuread/releases/165516355), so upgrading will fix this issue.

Duplicate of #1197.
