### ISSUE TITLE
Provider deprecated attribute even if we don't configure it

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi-azuread#164]
Using pulumi-azuread 4.1.0 I get the following warning:

```
    warning: provider config warning: Deprecated Attribute
```

I never actually configure the provider and I get no indication of what the attribute in question is. I'm assuming it's `metadata_host`, but I don't see it on the stack as well.

## Expected behavior

No warnings.

## Current behavior

I get a warning related to a default configuration.

## Steps to reproduce

Upgrade to pulumi-azuread 4.1.0 and just run anything.

**Comment by ekini** [comment]
Looks like it's related to https://github.com/hashicorp/terraform-provider-azuread/issues/437 and will be fixed in 1.5.1 version of the upstream provider.
