### ISSUE TITLE
Add support for Saml2Token OptionalClaims in Azure AD Application

### ISSUE THREAD

**Issue by pierrekhouryb** [pulumi/pulumi-azuread#174]
Azure allows setting 3 different optional claim types: idToken, accessToken and saml2Token. 
See: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#optionalclaims-type

Looking at Pulumi.AzureAD.Outputs, only idToken and accessToken seem to be supported:
https://github.com/pulumi/pulumi-azuread/blob/ace17ccb1de2b8308b03f8fbef73ee82fa5f99d8/sdk/dotnet/Outputs/ApplicationOptionalClaims.cs

saml2Token should be added to maintain 100% coverage of Azure. 

Ping @mikhailshilkov

**Comment by emiliza** [comment]
Upstream provider today just has support for accessToken and idToken https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application#optional_claims

When support gets added upstream we'll pull them in

**Comment by pierrekhouryb** [comment]
I see thanks @emiliza ! Are there any plans to implement Azure AD using the Native Azure provider instead of the terraform provider?

**Comment by mikhailshilkov** [comment]
> Are there any plans to implement Azure AD using the Native Azure provider instead of the terraform provider?

Long-term, we expect it to be integrated into the Azure Native provider but we don't have a timeline yet.
