### ISSUE TITLE
Import azuread group fails 

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-azuread#196]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Executing the pulumi import command for an AD Group:
`pulumi import azuread:index/group:Group my_group 00000000-0000-0000-0000-000000000000`

throws errors about requiring either security_enabled or mail_enabled being set even though they are set.
```
azuread:index:Group (my_go_group):
    error: azuread:index/group:Group resource 'my_group' has a problem: AtLeastOne: "mail_enabled": one of `mail_enabled,security_enabled` must be specified. Examine values at 'Group.MailEnabled'.
    error: azuread:index/group:Group resource 'my_group' has a problem: AtLeastOne: "security_enabled": one of `mail_enabled,security_enabled` must be specified. Examine values at 'Group.SecurityEnabled'.
    error: Preview failed: one or more inputs failed to validate
```
The error has been reproduced in Typescript and Go. So it is not language-specific.
And although probably not pertinent, terraform import for an azuread Group completes successfully.

### Steps to reproduce

1. Create an Azure AD group ("secret" type)
2. In a new folder, create a typescript project and add this code:
```
import * as pulumi from "@pulumi/pulumi";
import * as azuread from "@pulumi/azuread";

export const gottenGroup = pulumi.output(azuread.getGroup({
    displayName: "PUT_NAME_OF_CREATED_GROUP_HERE",
}));
```
3. Modify the code so `displayName` is set to the name of the group you created in step 1.
3. Run pulumi up.
This will create the stack you need to do the import into and do a getGroup for the group you will be importing so you can validate it has the various properties required.
4. Using the AD group's ID, from the command line, run `pulumi import azuread:index/group:Group my_group AD_GROUP_ID_TO_IMPORT`
e.g. `pulumi import azuread:index/group:Group my_group 000000-0000-0000-0000-000000000`
5. See the errors indicated above.

Tested with 
├── @pulumi/azuread@5.3.0 (known to exist in 5.2.0 as well)
├── @pulumi/pulumi@3.13.2
└── @types/node@10.17.60

Expected: 
I expected the import to run successfully, bring the resource into state and generate scaffolding code.

Actual: 
It failed with the errors indicated above.

**Comment by MitchellGerdisch** [comment]
This issue is dependent on https://github.com/pulumi/pulumi-terraform-bridge/issues/384

**Comment by mikhailshilkov** [comment]
Import functionality has been significantly refactored in https://github.com/pulumi/pulumi/issues/8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).
