### ISSUE TITLE
TypeScript vs C# API Differences

### ISSUE THREAD

**Issue by RehanSaeed** [pulumi/pulumi-azuread#226]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I've been following the [Kubernetes Crosswalk](https://www.pulumi.com/docs/guides/crosswalk/kubernetes/) guide which is written in TypeScript and am trying to follow in in C#. While trying to migrate the TypeScript version to C# I've discovered that there are several differences in the Azure AD API e.g.

1. `Pulumi.AzureAD.ApplicationArgs` does not have the `replyUrls` or `type` input property.
2. `Pulumi.AzureAD.ServicePrincipalPassword` does not have a `Value` or `EndDate` input property to set the password or its expiry.
3. `Pulumi.AzureAD.Assignment` does not have the `PrincipalId` or `RoleDefinitionName` input property.
4. `Pulumi.AzureAD.Group` does not have a `Name` input property.

The code I have been trying to port can be found here:

https://github.com/pulumi/kubernetes-guides/blob/master/azure/01-identity/index.ts

**Comment by stack72** [comment]
Hi @RehanSaeed 

Sorry for this guide being out of date - we recently had a major version update of the AzureAD provider so the SDKs do match but the sample code in the guide is out of date

I will get an issue filed on our guides repo to get this kept up to date

Paul
