### ISSUE TITLE
Creating new Application Results in 403

### ISSUE THREAD

**Issue by RehanSaeed** [pulumi/pulumi-azuread#246]
I am calling:

```cs
var app = new Pulumi.AzureAD.Application("foo", new ApplicationArgs() { DisplayName = "foo" });
```

And getting this error when calling `pulumi up`:

> Could not create application: ApplicationsClient.BaseClient.Post(): unexpected status 403 with OData error: 
> Authorization_RequestDenied: Insufficient privileges to complete the operation.

Running `pulumi up` with the `--debug` flag gives some extra information:

```
debug: ============================ Begin AzureAD Response ===========================
    debug: POST https://graph.microsoft.com/beta/[secret]/applications
    debug: Request ID: aaff5926-456a-ad1c-d4f6-7026cebe0853
    debug:
    debug: HTTP/1.1 403 Forbidden
    debug: Transfer-Encoding: chunked
    debug: Cache-Control: no-cache
    debug: Client-Request-Id: 00f6e50c-3ee8-4d52-881f-d469f5dd1f92
    debug: Content-Type: application/json
    debug: Date: Fri, 11 Feb 2022 09:26:31 GMT
    debug: Deprecation: Mon, 05 Apr 2021 23:59:59 GMT
    debug: Link: <https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=beta,PrivatePreview:Restricted_AU_Properties&from=2021-04-01&to=2021-05-01>;rel="deprecation";type="text/html"
    debug: Link: <https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=beta,PrivatePreview:HasExtendedValue&from=2021-10-01&to=2021-11-01>;rel="deprecation";type="text/html"
    debug: Link: <https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=beta,PrivatePreview:RequestSignatureVerification&from=2021-10-01&to=2021-11-01>;rel="deprecation";type="text/html"
    debug: Link: <https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=beta,PrivatePreview:RequestSignatureVerification&from=2021-10-01&to=2021-11-01>;rel="deprecation";type="text/html"
    debug: Link: <https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=beta,PrivatePreview:RequestSignatureVerification&from=2021-10-01&to=2021-11-01>;rel="deprecation";type="text/html"
    debug: Request-Id: 00f6e50c-3ee8-4d52-881f-d469f5dd1f92
    debug: Strict-Transport-Security: max-age=31536000
    debug: Sunset: Sat, 19 Feb 2022 23:59:59 GMT
    debug: Vary: Accept-Encoding
    debug: X-Ms-Ags-Diagnostic: {"ServerInfo":{"DataCenter":"UK South","Slice":"E","Ring":"3","ScaleUnit":"003","RoleInstance":"LO2PEPF000003E8"}}
    debug: X-Ms-Resource-Unit: 1
    debug:
    debug: 10a
    debug: {"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.","innerError":{"date":"2022-02-11T09:26:31","request-id":"00f6e50c-3ee8-4d52-881f-d469f5dd1f92","client-request-id":"00f6e50c-3ee8-4d52-881f-d469f5dd1f92"}}}
    debug: 0
    debug:
    debug:
    debug: ============================= End AzureAD Response ============================
```

Is this related to https://github.com/pulumi/pulumi-azuread/issues/185 or https://github.com/pulumi/pulumi-azuread/issues/68? Is there a workaround?

**Comment by RehanSaeed** [comment]
I'm using a service principal instead of using `az login` to run my Pulumi code. I now suspect that the service principal doesn't have the correct permissions to create applications or other service principals.

```powershell
az ad sp create-for-rbac --name foo --role Contributor
```

The above is the command I use to create the service principal. The [docs](https://www.pulumi.com/registry/packages/azuread/installation-configuration/) have no mention of providing additional permissions.

**Comment by danielrbradley** [comment]
I'd say this is probably a different issue from either of the two referenced issues as it's directly correlated to the identity making the call.

If the issue is limited to a specific identity then this would appear to be a role configuration issue rather than bug in the provider so will close here unless it appears the error is specific to this Pulumi provider.

I would suggest that when selecting the role for the service principal you might need additional priviliges. Here's a helpful page listing some of the additional built-in roles, though it's also possible to create custom roles too: https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles

**Comment by JaseKirby** [comment]
OK fair enough and that makes sense to me. I can say that it wasn't actually a matter of time like I initially stated, but rather this issue occurred on initial provisioning of the Azure AD application only when either `requiredResourceAccesses` or `optionalClaims` was defined so I was able to workaround the issue by commenting them out, provisioning the application, and then adding them in later through an update.

I don't know if that helps or not but just throwing it out there as the initial example defined neither of these properties.

**Comment by RehanSaeed** [comment]
I asked a question on StackOverflow to determine which role we need:

https://stackoverflow.com/questions/71079517/what-role-or-scopes-does-an-azure-service-principal-need-to-create-applications

Apparently, this is supposed to work:

```powershell
az ad sp create-for-rbac --name foo --role 'User Access Administrator'
```

However, I'm still getting a 403. @JaseKirby How did you solve this issue?

**Comment by dviry** [comment]
FYI - since it's using the graphApi/beta instance, I had to add the GraphAPI Application API Rights "Application.ReadWrite.All" - and consent it - to the registered App (in my case I was deploying Pulumi within a DevOps Pipeline with a Service Connection).

This solved the issue for me.
