### ISSUE TITLE
Go: Unable to update "pulumi-azuread" to "v5.18.0" due "unknown revision"

### ISSUE THREAD

**Issue by jotdl** [pulumi/pulumi-azuread#260]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I use the **go version** of this module and I am sadly unable to update to the version `v5.18.0` of `pulumi-azuread`.
Instead we always receive the following error:

```
❯ go mod download github.com/pulumi/pulumi-azuread/sdk/v5@v5.18.0
go: github.com/pulumi/pulumi-azuread/sdk/v5@v5.18.0: reading github.com/pulumi/pulumi-azuread/sdk/sdk/go.mod at revision sdk/v5.18.0: unknown revision sdk/v5.18.0
```

For `v5.17.0` this succeeds. 

## Assumption
I assume that this might be caused by having the tag for the `sdk` as [sdk/5.18.0](https://github.com/pulumi/pulumi-azuread/releases/tag/sdk%2F5.18.0) instead of `sdk/v5.18.0` (see the missing `v`). Previous versions had this `v`, e.g. [sdk/v5.17.0](https://github.com/pulumi/pulumi-azuread/releases/tag/sdk%2Fv5.17.0). I assume this based on the documentation of [Go Modules Reference > Mapping versions to commits](https://go.dev/ref/mod#vcs-version): 

### Steps to reproduce

1. `mkdir example && cd example`
2. `go mod init example.com`
3.  Append `require github.com/pulumi/pulumi-azuread/sdk/v5 v5.18.0` as a new line to `go.mod` 
4. Run `go mod download`

Expected: `go mod download` succeeds without any errors as it does for `v5.17.0`
Actual: 
```
❯ go mod download
go: github.com/pulumi/pulumi-azuread/sdk/v5@v5.18.0: reading github.com/pulumi/pulumi-azuread/sdk/sdk/go.mod at revision sdk/v5.18.0: unknown revision sdk/v5.18.0
```

Thanks a lot for your help!

**Comment by viveklak** [comment]
@jotdl thanks for reporting! Indeed this is because of a mistake tagging the last release. Retagged correctly now. Could you check and let us know if you are still running into this issue?

**Comment by jotdl** [comment]
@viveklak: Works now as expected. Thanks for fixing!
