### ISSUE TITLE
GetServicePrincipal issues a deprecation `warning` for an Output

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi-azuread#267]
### What happened?

When using the function GetFunctionPrincipal we get a deprecation `warning`:

```
warning: features is deprecated: This block has been renamed to `feature_tags` and will be removed in version 3.0 of the provider
```

But `features` is a part of the Outputs, not the Inputs, so we can't control any of it and the display appears all the time, which is annoying, specially if you need to call this function multiple times.

### Steps to reproduce

Sample code to reproduce behaviour, in Python:

```
import pulumi_azuread

pulumi_azuread.get_service_principal(display_name="Microsoft Graph")
```

### Expected Behavior

No deprecation warnings, or a way to bypass them.

### Actual Behavior

A deprecation warning appears.

### Versions used

CLI          
Version      3.28.0
Go Version   go1.17.8
Go Compiler  gc

Plugins
NAME          VERSION
aiven         4.5.0
aws           5.1.2
azure-native  1.62.0
azuread       5.19.0
opsgenie      1.1.5
python        unknown
random        4.4.2
tls           4.1.0

Host     
OS       ubuntu
Version  21.10
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @Sodki - thank you for filing this issue. We'll take a look when we can.
