### ISSUE TITLE
Cannot create azuread-provider using service-principal settings in configuration

### ISSUE THREAD

**Issue by Jan1503** [pulumi/pulumi-azuread#314]
### What happened?

I would like to use the azuread-provider to be able to create groups etc...

I configured the settings in the config like so:

```
azuread:clientId: xxx-xxxx-xxxxxx--xxx
  azuread:clientSecret:
    secure: v1:xxxxxxxxxxx
  azuread:subscriptionId: xxxxx
  azuread:tenantId: xxxxxx
```

A simple call to `current = azuread.get_client_config()` raises this error:

```
Diagnostics:
  pulumi:pulumi:Stack (Create-Subscription-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "D:\Repos\Python\Pulumi-Samples\Create-Subscription\.\__main__.py", line 49, in <module>
        current = azuread.get_client_config()
      File "D:\Repos\Python\Pulumi-Samples\Create-Subscription\venv\lib\site-packages\pulumi_azuread\get_client_config.py", line 102, in get_client_config
        __ret__ = pulumi.runtime.invoke('azuread:index/getClientConfig:getClientConfig', __args__, opts=opts, typ=GetClientConfigResult).value
      File "D:\Repos\Python\Pulumi-Samples\Create-Subscription\venv\lib\site-packages\pulumi\runtime\invoke.py", line 144, in invoke
        raise invoke_error
    Exception: invoke of azuread:index/getClientConfig:getClientConfig failed: invocation of azuread:index/getClientConfig:getClientConfig returned an error: could not validate provider configuration: 1 error occurred:
        * Invalid or unknown key
        *
```

I think it must be the subscriptionId setting cause this is not present in the providers constructor nor in the [terraform module documentation](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/service_principal_client_secret#environment-variables) but if I omit this I get the error that I have to specify this value:

```
Diagnostics:
  pulumi:pulumi:Stack (subscriptions-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "D:\Repos\azure-github-pg\src\subscriptions\.\__main__.py", line 83, in <module>
        current = azuread.get_client_config()
      File "D:\Repos\azure-github-pg\src\subscriptions\venv\lib\site-packages\pulumi_azuread\get_client_config.py", line 102, in get_client_config
        __ret__ = pulumi.runtime.invoke('azuread:index/getClientConfig:getClientConfig', __args__, opts=opts, typ=GetClientConfigResult).value
      File "D:\Repos\azure-github-pg\src\subscriptions\venv\lib\site-packages\pulumi\runtime\invoke.py", line 144, in invoke
        raise invoke_error
    Exception: invoke of azuread:index/getClientConfig:getClientConfig failed: invocation of azuread:index/getClientConfig:getClientConfig returned an error: failed to load application credentials.
    Details: 1 error occurred:
        * A Subscription ID must be configured when authenticating as a Service Principal using a Client Secret.
```

How do I create the provider successfully???
Using latest version of pulumi.

### Steps to reproduce

Simple but the four settings in your config and try to use the azuread-provider.

### Expected Behavior

The azuread-provider works as expected

### Actual Behavior

The azuread-provider cannot be created.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @Jan1503 - thank you for filing this bug. We'll look into it as soon as possible.

**Comment by rafaribe** [comment]
Happening to me also. If I set the `azuread:subscriptionId` then I get the following error:
```
azuread:index:Application (application):
    error: could not validate provider configuration: 1 error occurred:
        * Invalid or unknown key
```
If I don't set the `azuread:subscriptionId` then I get the following error:

```
 error: failed to load application credentials.
    Details: 1 error occurred:
        * A Subscription ID must be configured when authenticating as a Service Principal using a Client Secret.
```

**Comment by Jan1503** [comment]
Hmm, even with the latest version 3.44.0 the error is still present.
Have not tried a `pulumi up` yet but `pulumi preview` is definitely not working...
@rafaribe Could you verify on your side please...

**Comment by danielrbradley** [comment]
@Jan1503 Please can you check which versions of the plugin are actually being used. It could be that your state was created using the old version of the plugin, and therefore it'll still reference that version on the next run. 

If you're able to use a brand new project to reproduce the issue that would be the most reliable way to confirm where the issue lies.

**Comment by Jan1503** [comment]
@danielrbradley Hey Daniel, sorry for my late reply. I can confirm its working. My state-file was referencing the old versions.
