### ISSUE TITLE
Add member to Administrative Unit

### ISSUE THREAD

**Issue by sinePaul** [pulumi/pulumi-azuread#315]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Graph API now allows to create security groups as member of administrative unit but it is not possible to do so with Pulumi.
To add a security group as a member of an administrative unit with graph API, one has to use that endpoint `/directory/administrativeUnits/{id}/members`. It allows to give developer write access group in specifc administrative unit, instead of the entire Azure AD. 

### Affected area/feature

[MS documentation of the feature](https://learn.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-1.0&tabs=http#example-2-create-a-new-group)

**Comment by danielrbradley** [comment]
Hi @sinePaul thanks for the submission.

This is a bridged provider and so depends on the upstream terraform provider to implement the requested feature. It appears a similar issue has already been opened: https://github.com/hashicorp/terraform-provider-azuread/issues/906

Once that is resolved, we'll be able to adopt the change in our provider too.

**Comment by mikhailshilkov** [comment]
The upstream issue https://github.com/hashicorp/terraform-provider-azuread/issues/906 has been resolved via https://github.com/hashicorp/terraform-provider-azuread/pull/984
