### ISSUE TITLE
Allow OIDC Authentication Options

### ISSUE THREAD

**Issue by phantlantis** [pulumi/pulumi-azuread#530]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Hello - the Terraform AzureAD provider allows for OIDC configuration options to be passed into the provider - I see over here there are similar options that are [currently commented out](https://github.com/pulumi/pulumi-azuread/blob/38715047048da02406bd93efa85e1003c020269c/provider/resources.go#L139):
> // The configuration below would enable OIDC auth which we haven't tested and documented yet.
		//FederatedAssertion:        idToken,
		//IDTokenRequestURL:         d.Get("oidc_request_url").(string),
		//IDTokenRequestToken:       d.Get("oidc_request_token").(string),
		//EnableClientFederatedAuth: d.Get("use_oidc").(bool),
		//EnableGitHubOIDCAuth:      d.Get("use_oidc").(bool),

We have a use case that requires using OIDC auth in an Azure Devops pipeline - it would definitely be helpful if we could pass in an OIDC request URL and token to get an identity back, rather than having to rely on being logged into the CLI or on cert or secret authentication for a Service Principal.

If there is anything I can do to help test the use case for it, we have similarly working parameters currently set using the Pulumi Azure Native provider that I believe would essentially be relying on the same auth mechanisms under the hood. 

### Affected area/feature

The above linked code - and likely an update [to the provider docs](https://www.pulumi.com/registry/packages/azuread/installation-configuration/) as well to demonstrate usage of the configuration options.

**Comment by mikhailshilkov** [comment]
@thomas11 It sounds like we should do that soon. How hard would it be?

**Comment by thomas11** [comment]
> @thomas11 It sounds like we should do that soon. How hard would it be?

@mikhailshilkov As the submitter pointed out, there is already untested code. Testing will be most of the work. We can borrow the Github Workflows test from azure-native. If we wanted to test on Azure DevOps - which we probably should given the audience of this provider - that would be new.
