### ISSUE TITLE
PKCE enabled Applications

### ISSUE THREAD

**Issue by sindre-nistad** [pulumi/pulumi-azuread#92]
Is there an (easy) way to change the type of a reply URL for `pulumi_azuread.Application`?

In the Azure Portal, there are three main types (as used in the key `replyUrlsWithType` in the manifest) of redirect URIs; "Web", "Spa", and "native".
I've been unable to have the URIs be categorised as "Spa", as this is necessary to enable the PKCE code flow in Azure.

I am able to change it manually, and pulumi will not change it back, with I use as a workaround.

![Skjermbilde 2020-08-10 kl  18 59 14](https://user-images.githubusercontent.com/38072308/89809269-9d7d2800-db3b-11ea-85ab-a772e041bfab.png)

**Comment by leezen** [comment]
Tracked upstream in https://github.com/terraform-providers/terraform-provider-azuread/issues/286

**Comment by mastoj** [comment]
@leezen, any plans on fixing this or are we waiting for it to be fixed upstream?

**Comment by leezen** [comment]
Still waiting for this upstream, unfortunately.
